### ISSUE TITLE
Reverse mode?

### ISSUE THREAD

**Issue by sergiocorreia** [Eliasyoussef47/LockCursorInMonitor#15]
Would it be feasible to have a reverse mode, where the mouse is locked to the primary monitor unless you press the CTRL key? So it would work exactly as before but with the Ctrl key having the opposite effect.

**Is your modification request related to a problem? Please describe.**

Yes. I go to the right side of my screen _a lot_, to check notifications, close/maximize/drag screens, etc, but only go to the second monitor once in a while (I use it in layout mode for email, reading PDFs, command line, etc.). So for me it would be way more useful to disallow entirely moving the mouse to the second monitor _unless_ Ctrl is pressed.

**Describe the solution you'd like**

An extra toggle where I can activate "Reverse mode" (or whatever would be a good name for it)

**Describe alternatives you've considered**

I gave the normal mode a try for a few days, but having to press Ctrl every time I move the mouse to the right felt too unnatural and I always kept forgetting

**Comment by Eliasyoussef47** [comment]
Hi.

I actually made this app because everywhere I looked I couldn't find anything that does exactly what I wanted. Everything that I found did exactly what you are describing (if I'm understanding correctly). You can find some good suggestions in this link: https://superuser.com/questions/1088286/how-to-restrict-mouse-to-current-display
(You can even see my answer)

**Comment by sergiocorreia** [comment]
Thanks for the prompt reply, I'll try the other tools! But still, yours feels much more smooth that the other ones (e.g. DMT) with 1000 unrelated options, so there's still some value to the option IMO (but of course, adding options is always a slippery slope!)
